### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by dereuromark** [liqueurdetoile/cakephp-orm-json#1]
May I offer a few improvement tips?

https://github.com/liqueurdetoile/cakephp-orm-json/blob/master/src/ORM/JsonQuery.php#L142
Most json...() methods are nice camelBacked, but `jsonselect` is not, I recommend consistency using `jsonSelect` method name, same for `jsonwhere` => `jsonWhere`.

Adding doc blocks everywhere with the full param and return type declaration helps devs and the IDEs/tooling to work with this better ( e.g. https://github.com/liqueurdetoile/cakephp-orm-json/blob/master/src/Model/Entity/JsonTrait.php#L33 )

You can add phpstan here to verify some of the basic implementation details are all good.
See also [this](https://www.dereuromark.de/tag/phpstan/) and since you also support 3.5 [this](https://www.dereuromark.de/2018/03/14/cakephp-3-6-is-coming/#prepare-your-plugins).

**Comment by liqueurdetoile** [comment]
Thanks a lot for the tips and hints !

I've changed naming conventions as proposed (stile wondering why i did name like that ?!), complete doc and added phpstan. No error at level 5 by now (it was phpdoc issues in fact).

Release 1.0.0 is out !

**Comment by dereuromark** [comment]
Replacing existing tags is dangerous, better to use 1.0.1 than
But glad if it works.

**Comment by liqueurdetoile** [comment]
I agree. But I was the only user at this stage so no harm to perform a fresh start
