### ISSUE TITLE
CAKEPHP 4

### ISSUE THREAD

**Issue by TheSwindler44** [liqueurdetoile/cakephp-orm-json#6]
Hi,

I'm wondering if this plugin will be or is supported under CakePHP 4.x.
Your plugin is one of a kind and I haven't been able to find anything like it anywhere else. I am hoping the support will continue.

**Comment by waspinator** [comment]
The 2.0 version of this library supports cake 4

https://github.com/liqueurdetoile/cakephp-orm-json/blob/2.0.0-dev/composer.json

**Comment by DJAxel** [comment]
@waspinator The readme file says it's still for `CakePHP 3.5+`. Does your answer mean that this value should be changed to `4.x`?

**Comment by liqueurdetoile** [comment]
@TheSwindler44 Version 2 should be OK with PHP 4. I must dig in to see if I can make a regular release in next weeks.

**Comment by liqueurdetoile** [comment]
Sorry to be so late.... 😪
